---
title: "Introduction  to tidyGenomeBrowser"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction  to tidyGenomeBrowser}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(tidyGenomeBrowser)
```

# Introduction

TBA

# Overview of functions:

## Method diagram

```{r mermaid, echo=FALSE, fig.width=10, fig.height=10, fig.cap="Overview of methods for each generic: Square = S4-object, circle = S3-object, Diamond = Random access filess"}
DiagrammeR::mermaid("graph LR
   TabixFile1{TabixFile}
   TabixFileList1{TabixFileList}
   TabixFile2{TabixFile}
   TabixFileList3{TabixFileList}
   TabixFile3{TabixFile}
   BigWigFile{BigWigFile}
   BigWigFileList{BigWigFileList}

   GRanges1[GRanges]
   GRanges2[GRanges / GPos]
   GPos[GPos]

   GRangesList1[GRangesList]
   GRangesList2[GRangesList / GPosList]
   GRangesList3[GRangesList]
   GPosList[GPosList]

   data.frame1((data.frame))
   data.frame2((data.frame))
   data.frame3((data.frame))
   data.frame4((data.frame))
   data.frame5((data.frame))


   ggplot1((ggplot))
   ggplot2((ggplot))
   ggplot3((ggplot))
   ggplot4((ggplot))
   ggplot5((ggplot))


   ggplots>ggplots]

   TabixFile1 --> GRanges1
   TabixFileList1 --> GRangesList1
   GRanges1 --> data.frame1
   GRangesList1 --> data.frame1
   data.frame1 --> ggplot1

   BigWigFile --> GRanges2
   BigWigFileList --> GRangesList2
   GRanges2 --> data.frame2
   GRangesList2 --> data.frame2
   data.frame2 --> ggplot2

   TxDB --> GRangesList3
   GRangesList3 --> data.frame3
   data.frame3 --> ggplot3

   TabixFile2 --> GInteractions
   GInteractions --> data.frame4
   data.frame4 --> ggplot4

   TabixFile3 --> GPos
   TabixFileList3 --> GPosList
   GPos --> data.frame5
   GPosList --> data.frame5
   data.frame5 --> ggplot5

   ggplot1 --> ggplots
   ggplot2 --> ggplots
   ggplot3 --> ggplots
   ggplot4 --> ggplots
   ggplot5 --> ggplots

subgraph browseTxs
    TxDB
    GRangesList3
    data.frame3
    ggplot3
end

subgraph browseInteractions
    TabixFile2
    GInteractions
    data.frame4
    ggplot4
end

subgraph browseSignal
    BigWigFile
    BigWigFileList
    GRanges2
    GRangesList2
    data.frame2
    ggplot2
end

subgraph browseIntervals
    TabixFile1
    TabixFileList1
    GRanges1
    GRangesList1
    data.frame1
    ggplot1
end

subgraph browsePositions
    TabixFile3
    TabixFileList3
    GPos
    GPosList
    data.frame5
    ggplot5
end

subgraph browseStack
    ggplots
end")
```

## Package-wide settings:

- alpha
- strand colors
- interaction colors.

## Reserved column names:

- GenomicRanges: `seqnames`, `start`, `end`, `strand`.
- rtracklayer: `score`, `thick`, `thickStart`, `thickEnd`.
- ggplot: `color`, `facet`.
- IntearactionSet: `bezier`, `bezierx`, `beziery`.